### PR TITLE
Allow user to specify project directory

### PR DESCRIPTION
**Pull request by dejagersh**
I have several javascript applications nested in my project, each having their own eslint configurations. I would like to be able to specify the directory in which the linting is done.

### CODE REVIEW

**Comment by mskadu** [comment]
Thanks for teaming up here @thejager - I am grateful for your prompt actions. As I've said, this is of interest to me - since all of my projects have node.js projects nested under the main one as sub-folders.

**Comment by darshkpatel** [comment]
+1 on this, I was planning to fork and add this feature when i came across this PR. 
I have multiple projects under multiple sub directories , would be helpful to specify directory

**Comment by dejagersh** [comment]
@hallee can you merge this?

**Comment by hallee** [comment]
Hi @thejager, thanks for the PR.

https://github.com/hallee/eslint-action/pull/3 also has project directory support along with a couple other features, so I'm going to try to get that PR merged instead.

**Comment by dejagersh** [comment]
Ah I didn't even see that. Perfect, thanks!

Feel free to close this PR when you see fit.

**Pull request closed without merging**
