### PR TITLE
fix your dog food :D

### PR DESCRIPTION
**Pull request by MichaelSp**

### CODE REVIEW

**Comment by MichaelSp** [comment]
Oh crap! :/

>OAuth tokens and GitHub Apps are restricted from editing the main.workflow file. This means it isn't possible to merge a Pull Request via an Action if it updates the main.workflow file I'm afraid.
This is expected behaviour currently but we'll pass your feedback onto the team to consider.

https://github.community/t5/GitHub-Actions/GitHub-action-Resource-not-accessible-by-integration/td-p/19707

**Comment by hallee** [comment]
This action supports both `env` and the `repo-token` variable. No need to change it.

**Comment by MichaelSp** [comment]
hmm still wondering why it's broken: https://github.com/hallee/eslint-action/actions

**Comment by hallee** [comment]
Actions run on forks cannot access the `GITHUB_TOKEN` of the origin repository, so this action will fail on forks. Maybe I should have a graceful did-not-run state rather than an error in that case

**Pull request closed without merging**
